# Generated by Django 4.2.3 on 2023-07-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_workout',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='matricula',
        ),
        migrations.AddField(
            model_name='current_workout',
            name='current_workout_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='current_workout', to='cadastro.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='cadastro.person'),
            preserve_default=False,
        ),
    ]
