# Generated by Django 4.2.3 on 2023-07-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('treino', '0004_alter_workout_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_workout',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treino.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='cadastro.person'),
        ),
        migrations.AlterField(
            model_name='workout_exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='treino.workout'),
        ),
    ]
