# Generated by Django 4.2.3 on 2023-07-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0004_alter_exercise_name_alter_exercise_type'),
        ('treino', '0005_alter_current_workout_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_exercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercise'),
        ),
    ]
