# Generated by Django 4.2.3 on 2023-08-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0008_remove_current_workout_current_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='current_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Atual quantidade'),
        ),
    ]
