# Generated by Django 4.2.3 on 2023-08-03 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0009_alter_workout_current_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(max_length=1, validators=[django.core.validators.MaxLengthValidator(limit_value=1)], verbose_name='Nome do treino'),
        ),
    ]
