# Generated by Django 4.2.3 on 2023-07-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('birthDate', models.DateField(verbose_name='Data de nascimento')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Possui whatsapp?')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('', 'Planos'), ('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=10, verbose_name='Nome do plano')),
                ('signature_date', models.DateField(auto_now=True, verbose_name='Data de assinatura')),
                ('expiration_date', models.DateField(verbose_name='Data de expiração')),
                ('plan_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='cadastro.person')),
            ],
        ),
        migrations.CreateModel(
            name='addressPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('street', models.CharField(max_length=30, verbose_name='Rua')),
                ('neighborhood', models.CharField(max_length=30, verbose_name='Bairro')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('complement', models.CharField(max_length=30, verbose_name='Complemento')),
                ('address_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='cadastro.person')),
            ],
        ),
    ]
