# Generated by Django 4.2.3 on 2023-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_person_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='templates/static/profileImages', verbose_name='Imagem de perfil'),
        ),
    ]
