# Generated by Django 4.2.3 on 2023-07-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='tipo',
            new_name='type',
        ),
    ]
