# Generated by Django 4.2.3 on 2023-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_rename_tipo_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Máquina', 'Máquina'), ('Corporal', 'Corporal')], max_length=8),
        ),
    ]
