# Generated by Django 4.2.3 on 2023-07-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_alter_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('', 'Tipos'), ('Máquina', 'Máquina'), ('Corporal', 'Corporal')], max_length=8, verbose_name='Tipo'),
        ),
    ]
